---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg16
  namespace: postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2-3
  postgresql:
    parameters:
      # to mimic 'replication slot cannot be advanced' Error 
      max_slot_wal_keep_size: "64MB"
      wal_keep_size: "0"
      # to frequently trigger checkpoints and promote WAL recycling
      min_wal_size: "32MB"
      max_wal_size: "64MB"
      checkpoint_timeout: "30s"
  storage:
    size: 1Gi
